
/**
 * This was generated by https://quicktype.io
 * https://developer.clickup.com/reference/gettasks
 */
export interface Gettasks {
    id:               string;
    custom_id:        null;
    custom_item_id:   number;
    name:             string;
    text_content:     string;
    description:      string;
    status:           Status;
    orderindex:       string;
    date_created:     string;
    date_updated:     string;
    date_closed:      null;
    date_done:        null;
    archived:         boolean;
    creator:          Creator;
    assignees:        any[];
    group_assignees:  any[];
    watchers:         Creator[];
    checklists:       any[];
    tags:             any[];
    parent:           null;
    top_level_parent: null;
    priority:         null;
    due_date:         null;
    start_date:       null;
    points:           null;
    time_estimate:    null;
    custom_fields:    any[];
    dependencies:     any[];
    linked_tasks:     any[];
    locations:        any[];
    team_id:          string;
    url:              string;
    sharing:          Sharing;
    permission_level: string;
    list:             Folder;
    project:          Folder;
    folder:           Folder;
    space:            Space;
}

export interface Creator {
    id:             number;
    username:       string;
    color:          string;
    email:          string;
    profilePicture: null;
    initials?:      string;
}

export interface Folder {
    id:      string;
    name:    string;
    hidden?: boolean;
    access:  boolean;
}

export interface Sharing {
    public:                  boolean;
    public_share_expires_on: null;
    public_fields:           string[];
    token:                   null;
    seo_optimized:           boolean;
}

export interface Space {
    id: string;
}

export interface Status {
    status:     string;
    id:         string;
    color:      string;
    type:       string;
    orderindex: number;
}
